### ISSUE TITLE
.net database

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#2657]
dont know if this affect anything but i get this error in .net database

crit: MultiplayerARPG.MMO.MySQLDatabase[0]
      MySqlConnector.MySqlException (0x80004005): Column 'currentChannel' cannot be null
         at MySqlConnector.Core.ServerSession.ReceiveReplyAsync(IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ServerSession.cs:line 885
         at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in /_/src/MySqlConnector/Core/ResultSet.cs:line 37
         at MySqlConnector.MySqlDataReader.ActivateResultSet(CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 130
         at MySqlConnector.MySqlDataReader.InitAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, IDictionary`2 cachedProcedures, IMySqlCommand command, CommandBehavior behavior, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 482
         at MySqlConnector.Core.CommandExecutor.ExecuteReaderAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, CommandBehavior behavior, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/CommandExecutor.cs:line 56
         at MySqlConnector.MySqlCommand.ExecuteNonQueryAsync(IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlCommand.cs:line 309
         at MultiplayerARPG.MMO.MySQLDatabase.ExecuteNonQuery(MySqlConnection connection, MySqlTransaction transaction, Boolean isAsync, String sql, MySqlParameter[] args) in C:\Users\hubla\Desktop\UnityMultiplayerARPG_DatabaseManager\DatabaseManagerSource\MySQL\MySQLDatabase.cs:line 268

**Comment by moepi2k** [comment]
I think same for .net config folder. Its lowercase but should be upper case else it creates a new one for linux

**Comment by insthync** [comment]
It is because the .NET repo is outdated, or you are not pull its submodules, that is it.
