### ISSUE TITLE
Building Objects and building storage items not saved .net db

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#2667]
building -> extradata default should be allowed to be null

ALTER TABLE buildings MODIFY COLUMN extraData TEXT NULL;

```
crit: MultiplayerARPG.MMO.MySQLDatabase[0]
      MySqlConnector.MySqlException (0x80004005): Column 'extraData' cannot be null
         at MySqlConnector.Core.ServerSession.ReceiveReplyAsync(IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ServerSession.cs:line 885
         at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in /_/src/MySqlConnector/Core/ResultSet.cs:line 37
         at MySqlConnector.MySqlDataReader.ActivateResultSet(CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 130
         at MySqlConnector.MySqlDataReader.InitAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, IDictionary`2 cachedProcedures, IMySqlCommand command, CommandBehavior behavior, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 482
         at MySqlConnector.Core.CommandExecutor.ExecuteReaderAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, CommandBehavior behavior, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/CommandExecutor.cs:line 56
         at MySqlConnector.MySqlCommand.ExecuteNonQueryAsync(IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlCommand.cs:line 309
         at MultiplayerARPG.MMO.MySQLDatabase.ExecuteNonQuery(MySqlConnection connection, MySqlTransaction transaction, Boolean isAsync, String sql, MySqlParameter[] args) in C:\Users\hubla\Desktop\UnityMultiplayerARPG_DatabaseManager\DatabaseManagerSource\MySQL\MySQLDatabase.cs:line 268
```

**Comment by moepi2k** [comment]
ok thats not working ^^.. it save that building obj but server cant start anymore. alot of error while try load the building data

**Comment by moepi2k** [comment]
hmm i see in postgreSQL is already a null check for extradata

      string extraData = building.ExtraData;
      if (string.IsNullOrEmpty(extraData))
          extraData = "";

so i dont know why i get this error then

**Comment by moepi2k** [comment]
ok small summary. i tested with and without .net database

with .net database
-> building object not save in db
-> item in storage not save in db

without .net database
-> building object save in db
-> item in storage not save in db

i see alot of changes in MapNetworManager_DatabaseFunction.cs and as last report i send me the line of code which fixed to save item in storage https://github.com/suriyun-production/mmorpg-kit-docs/issues/2591

but now its broken again

**Comment by insthync** [comment]
fixed, try to find codes from mmo, .net repos

**Comment by moepi2k** [comment]
ok its working. but in .net i got this error

https://gyazo.com/e6f30a2044c5e1e59f7d86a4d05cbf14

**Comment by insthync** [comment]
It is because the .NET repo is outdated, or you are not pull its submodules, that is it.
